---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/terassyi/test-server:0.1.2
---
# LoadBalancer Service
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: test
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 80
      targetPort: 8080
