apiVersion: v1
kind: Pod
metadata:
  name: test-worker-non-default
  namespace: test
  annotations:
    sart.terassyi.net/addresspool: non-default-pod-pool
spec:
  containers:
  - name: test
    image: ghcr.io/terassyi/test-server:0.1.2
  nodeSelector:
    kubernetes.io/hostname: sart-worker
