apiVersion: v1
kind: Namespace
metadata:
  name: test-non-default
  labels:
    name: test
  annotations:
    sart.terassyi.net/addresspool: non-default-pod-pool
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker2-non-default
  namespace: test-non-default
spec:
  containers:
  - name: test-non-default
    image: ghcr.io/terassyi/test-server:0.1.2
  nodeSelector:
    kubernetes.io/hostname: sart-worker2
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker3-non-default
  namespace: test-non-default
spec:
  containers:
  - name: test
    image: ghcr.io/terassyi/test-server:0.1.2
  nodeSelector:
    kubernetes.io/hostname: sart-worker3
