apiVersion: v1
kind: Pod
metadata:
  name: test-cp
  namespace: test
spec:
  containers:
  - name: test
    image: ghcr.io/terassyi/test-server:0.1.2
  nodeSelector:
    kubernetes.io/hostname: sart-control-plane
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker
  namespace: test
spec:
  containers:
  - name: test
    image: ghcr.io/terassyi/test-server:0.1.2
  nodeSelector:
    kubernetes.io/hostname: sart-worker
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker2
  namespace: test
spec:
  containers:
  - name: test
    image: ghcr.io/terassyi/test-server:0.1.2
  nodeSelector:
    kubernetes.io/hostname: sart-worker2
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker3
  namespace: test
spec:
  containers:
  - name: test
    image: ghcr.io/terassyi/test-server:0.1.2
  nodeSelector:
    kubernetes.io/hostname: sart-worker3
---
apiVersion: v1
kind: Pod
metadata:
  name: test-worker3-2
  namespace: test
spec:
  containers:
  - name: test
    image: ghcr.io/terassyi/test-server:0.1.2
  nodeSelector:
    kubernetes.io/hostname: sart-worker3
