apiVersion: v1
kind: Pod
metadata:
  name: test-worker3-3
  namespace: test
spec:
  containers:
  - name: test
    image: ghcr.io/terassyi/test-server:0.1.2
  nodeSelector:
    kubernetes.io/hostname: sart-worker3
