apiVersion: sart.terassyi.net/v1alpha1
kind: BGPAdvertisement
metadata:
  name: adv-cluster
  namespace: kube-system
spec:
  network: 192.168.1.1/32
  nodes:
    - devenv-worker
    - devenv-worker2
---
apiVersion: sart.terassyi.net/v1alpha1
kind: BGPAdvertisement
metadata:
  name: adv-local-worker
  namespace: kube-system
spec:
  network: 192.168.1.2/32
  nodes:
    - devenv-worker
