apiVersion: sart.terassyi.net/v1alpha1
kind: ClusterBGP
metadata:
  labels:
    app.kubernetes.io/name: clusterbgp
    app.kubernetes.io/instance: clusterbgp-sample
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: controller
  name: clusterbgp-sample
spec:
  # TODO(user): Add fields here
