apiVersion: v1
kind: ConfigMap
metadata:
  name: sartd-fib-config
  namespace: kube-system
data:
  fib-config.yaml: |
    endpoint: 127.0.0.1:5001
    channels:
      - name: bgp-to-kernel
        ip_version: ipv4
        subscribers:
          - protocol: bgp
            endpoint: 127.0.0.1:5010
        publishers:
          - protocol: kernel
            tables:
              - 254
