apiVersion: apps/v1
kind: Deployment
metadata:
  name: sart-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: controller
          args:
            - controller
            - --mode=cni
      hostNetwork: true
      priorityClassName: system-cluster-critical
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      - key: node.kubernetes.io/not-ready
        effect: NoSchedule
