ARG RUST_VERSION=1.72.0

FROM rust:${RUST_VERSION} as builder

WORKDIR /home
COPY . /home/

RUN apt update -y && \
	apt install -y tcpdump iproute2 iputils-ping net-tools protobuf-compiler libprotobuf-dev mold
RUN make build

FROM debian:stable

RUN apt update -y && \
	apt install -y tcpdump iproute2 iputils-ping net-tools

COPY --from=builder /home/sartd/target/debug/sartd /usr/local/bin/sartd
COPY --from=builder /home/sart/target/debug/sart /usr/local/bin/sart
