apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cluster3
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-cluster3
  template:
    metadata:
      labels:
        app: app-cluster3
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-local2
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-local2
  template:
    metadata:
      labels:
        app: app-local2
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - containerPort: 80
---
# LoadBalancer Service
apiVersion: v1
kind: Service
metadata:
  name: app-svc-cluster3
  namespace: test
  annotations:
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: app-cluster3
  ports:
    - name: http
      port: 80
      targetPort: 80
---
# LoadBalancer Service
apiVersion: v1
kind: Service
metadata:
  name: app-svc-local2
  namespace: test
  annotations:
    sart.terassyi.net/addresspool: non-default-lb-pool
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: app-local2
  ports:
    - name: http
      port: 80
      targetPort: 80
