apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: sartd
    component: bgp
  name: sartd-bgp
  namespace: system
spec:
  selector:
    matchLabels:
      app: sartd
      component: bgp
  template:
    metadata:
      annotations:
        prometheus.io/port: "7472"
        prometheus.io/scrape: "true"
      labels:
        app: sartd
        component: bgp
    spec:
      containers:
        - command: ["sartd"]
          args:
            - bgp
            - --exporter=127.0.0.1:5003
          env:
            - name: SARTD_BGP_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          image: sart:dev
          imagePullPolicy: IfNotPresent
          name: bgp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_RAW
              drop:
                - ALL
            readOnlyRootFilesystem: true
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      # serviceAccountName: sartd
      terminationGracePeriodSeconds: 2
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoSchedule
          operator: Exists
