[package]
name = "sartd-cert"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["derive"] }
rcgen = "0.12.0"
rustls = "0.21.9"
rustls-pemfile = "1.0.4"
time = "0.3.30"
