resources:
  - ../default
patchesStrategicMerge:
  - ./manager.yaml
  - ./speaker.yaml

images:
  - name: sart:dev
    newName: localhost:5005/sart
    newTag: dev
  - name: sart-controller:dev
    newName: localhost:5005/sart-controller
    newTag: dev
