apiVersion: apps/v1
kind: Deployment
metadata:
  name: sart-controller
  namespace: system
spec:
  template:
    spec:
      securityContext: null
      containers:
        - command:
            - /manager
          args: null
          name: manager
          securityContext: null
          resources: null
