apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: sartd
    component: bgp
  name: sartd-bgp
spec:
  selector:
    matchLabels:
      app: sartd
      component: bgp
  template:
    spec:
      containers:
      - name: sartd
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
