apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  disableDefaultCNI: true
  serviceSubnet: "10.101.0.0/16"
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
