# permissions for end users to edit bgpadvertisements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bgpadvertisement-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: bgpadvertisement-editor-role
rules:
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgpadvertisements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgpadvertisements/status
  verbs:
  - get
