---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sart-terassyi-net-v1alpha1-bgpadvertisement
  failurePolicy: Fail
  name: vbgpadvertisement.kb.io
  rules:
  - apiGroups:
    - sart.terassyi.net
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bgpadvertisements
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sart-terassyi-net-v1alpha1-nodebgp
  failurePolicy: Fail
  name: vnodebgp.kb.io
  rules:
  - apiGroups:
    - sart.terassyi.net
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodebgps
  sideEffects: None
