[package]
name = "sartd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
rstest = "0.15.0"
tokio = { version = "=1.21.1", features = ["full"] }
tokio-stream = { version = "0.1.10", features = ["net"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tokio-io = "0.1.13"
futures = "0.3.24"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = "3.2.22"
bytes = "1.2"
byteorder = "1.4"
ipnet = "2.5.0"
socket2 = "0.4.7"
tonic = "0.8.2"
prost = "*"
tonic-reflection = "0.5.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json"] }

[build-dependencies]
tonic-build = {version = "0.8.2", features = ["prost"]}
