apiVersion: sart.terassyi.net/v1alpha2
kind: ClusterBGP
metadata:
  name: clusterbgp-sample-c
spec:
  nodeSelector:
    bgp2: c
  asnSelector:
    from: label
  routerIdSelector:
    from: internalAddress
  speaker:
    path: 127.0.0.1:5000
    multipath: true
  peers:
    - peerConfig:
        asn: 65000
        addr: 7.7.7.7
        groups:
          - to-router1
      nodeBGPSelector:
        bgp2: c
