apiVersion: apps/v1
kind: Deployment
metadata:
  name: sart-controller
  namespace: system
  labels:
    app.kubernetes.io/name: sart-controller
spec:
  template:
    metadata:
      labels:
        control-plane: sart-controller
    spec:
      containers:
        - name: sart-controller
          image: sart-controller:dev
