[package]
name = "sartd-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic-build = "0.10.2"
tonic = "0.10.2"
prost = "0.12.3"
prost-types = "0.12.3"

[build-dependencies]
tonic-build = { version = "0.10.2", features = ["prost"] }
