resources:
  - lb_cluster.yaml
  - lb_local.yaml
  - speaker.yaml
  - controller.yaml
  - ../rbac

images:
  - name: sart:dev
    newName: sart
    newTag: dev
  - name: controller:dev
    newName: sart-controller
    newTag: dev
