apiVersion: apps/v1
kind: Deployment
metadata:
  name: sart-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: controller
          args:
            - controller
            - --mode=dual
