name: ci
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  TAGS: dev

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.1"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/sartd/.cargo/registry
            ~/sartd/.cargo/git
            sartd/target
            ~/sart/.cargo/registry
            ~/sart/.cargo/git
            sart/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup dev
        run: make setup-dev
      - name: Setup grpc
        run: make setup-grpc
      - name: Fmt
        run: make fmt
      - name: Build
        run: make build
      - name: Run unit tests
        run: make unit-test
      - name: Run controller envtest
        run: make controller-test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.1"
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/head/main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build sartd and load
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.dev
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: sart:${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build sart-controller and load
        uses: docker/build-push-action@v2
        with:
          context: ./controller
          file: ./controller/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: sart-controller:${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build test-app and load
        uses: docker/build-push-action@v2
        with:
          context: ./controller/test/testapp/Dockerfile
          file: ./controller/test/testapp
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: test-app:${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: List images
        run: |
          docker images ls
      - name: Run e2e test
        run: make e2e-test
