name: ci
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  TAGS: dev

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.1"
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/sartd/.cargo/registry
            ~/sartd/.cargo/git
            sartd/target
            ~/sart/.cargo/registry
            ~/sart/.cargo/git
            sart/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run FRR
        run: |
          docker run -d --rm --name frr-test --privileged --volume /home/runner/work/sart/sart/e2e/sartd/data/simple/node2:/etc/node2 ghcr.io/terassyi/terakoya:0.1.2 tail -f /dev/null
          docker exec -d frr-test /usr/lib/frr/frrinit.sh start
          docker ps
          sleep 60
          docker exec -t frr-test gobgpd -f /etc/node2/config_zebra.toml
          docker ps
      - name: Setup dev
        run: make setup-dev
      - name: Setup grpc
        run: make setup-grpc
      - name: Fmt
        run: make fmt
      - name: Build
        run: make build
      - name: Run unit tests
        run: make unit-test
      - name: Run controller envtest
        run: make controller-test

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.1"
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/head/main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and load
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.dev
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: sart:${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: List images
        run: |
          docker images ls
      - name: Run e2e test
        run: make e2e-test
