name: Release
on:
  push:
    tags:
      - "v*"
defaults:
  run:
    working-directory: .
env:
  cache-version: 1
jobs:
  sart-image:
    name: Push sart container image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/head/main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Tag
        id: set-tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT # Remove "v" prefix.
      - name: Build and Push sartd
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/terassyi/sart:${{ steps.set-tag.outputs.RELEASE_TAG }}
  release:
    name: Release on GitHub
    needs:
      - sart-image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Kustomize build
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: "5.0.1"
          kustomize_build_dir: controller/config/release
          kustomize_comment: false
          kustomize_output_file: ./sart-controller.yaml
      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release v${{ github.ref }}
          files: sart-controller.yaml
