---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: sart
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices/finalizers
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sart.terassyi.net
  resources:
  - addresspools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sart.terassyi.net
  resources:
  - addresspools/finalizers
  verbs:
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - addresspools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - addressblocks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sart.terassyi.net
  resources:
  - addressblocks/finalizers
  verbs:
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - addressblocks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - blockrequests 
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sart.terassyi.net
  resources:
  - blockrequests/finalizers
  verbs:
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - blockrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgpadvertisements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgpadvertisements/finalizers
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgpadvertisements/status
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgppeer/status
  verbs:
  - get
  - list
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgppeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgppeers/finalizers
  verbs:
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgppeers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgppeertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgppeertemplates/finalizers
  verbs:
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - bgppeertempaltes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - clusterbgps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sart.terassyi.net
  resources:
  - clusterbgps/finalizers
  verbs:
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - clusterbgps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - nodebgps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sart.terassyi.net
  resources:
  - nodebgps/finalizers
  verbs:
  - update
- apiGroups:
  - sart.terassyi.net
  resources:
  - nodebgps/status
  verbs:
  - get
  - patch
  - update
